### ISSUE TITLE
Flatpak manifest

### ISSUE THREAD

**Issue by zocker-160** [giantpinkrobots/bootqt#1]
I have created a flatpak manifest which "works" (aka the application does launch)
[bootqt_flatpak.zip](https://github.com/giantpinkrobots/bootqt/files/8710390/bootqt_flatpak.zip)

![Screenshot_20220517_192536](https://user-images.githubusercontent.com/36563538/168874307-d593f777-f88d-4436-9585-f403c16f45f0.png)

In terms of functionality it will be problematic, because you are trying to run commands on the host using `lsblk_output = os.popen("lsblk").read()` and others, which is a bit of an issue inside a Flatpak because of the sandboxing.

With `- --filesystem=host` and `- --device=all` I gave it the highest possible permissions, so it might work, but I have not tested it.

For testing, you need to build the flatpak with
`flatpak-builder --force-clean --user --install build/ com.github.giantpinkrobots.bootqt.yml`

and then you run it with
`flatpak run com.github.giantpinkrobots.bootqt`

**Comment by giantpinkrobots** [comment]
Hello. First of all, thank you very much. I have built and ran it, and my usb drive does show up in the Select Drive menu, which means the `lsblk_output = os.popen("lsblk").read()` code works. But the actual writing process using QProcess does not start when I click Prepare Drive. I guess the sandboxing does not affect os.popen, but does affect QProcess?

**Comment by zocker-160** [comment]
I think the `lsblk` command works, because it is part of the KDE runtime inside the sandbox. 

There is a way to run commands on the host though using `flatpak-spawn --host <command>`. For that to work you need to add following permission: `--talk-name=org.freedesktop.Flatpak`

**Comment by giantpinkrobots** [comment]
Oh my god it works! I uploaded a separate flatpak version now, and edited the yml file accordingly. Thank you so so much! I will look at how to release it on Flathub now.

**Comment by zocker-160** [comment]
For flathub you need to create an appstream / metainfo file so it can generate the store page.
Then you should be set.

If you have any questions or need help, feel free to just tag me here.
